version: '3.4'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - ./:/app
  backendapp:
    image: backendapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - mongodb
    depends_on:
      - mongodb

